sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_5bdd6f1eeb19_key -iv $encrypted_5bdd6f1eeb19_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DevHub
script:
# 1. test with scratch org
- sfdx force:org:create -v DevHub -s -f config/project-scratch-def.json -a ciorg --wait 3
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p

# 2. create package version
#- sfdx force:package:version:create -p GIFter -d force-app/main -k test1234 --wait 10 -v DevHub

# 3. deploy to production org
- sfdx force:package:install -u MyProduction --wait 10 --package GIFter@1.1.0-3 -k test1234 --noprompt
#- sfdx force:user:permset:assign -n GIFter -u MyProduction
#- sfdx force:org:open -p lightning/n/GIFter -u MyProduction

